language: node_js
node_js:
  - 'node'

notifications:
  email: false

cache:
  yarn: true

before_install:
  - export TZ="Asia/Shanghai"
  - date

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install --frozen-lockfile

script:
  - yarn run build
  - yarn run try-demo
  - yarn run try-demo-js
  - node ./demo/check-two-result.js
  # - yarn run coverage

deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  skip_cleanup: true
  on:
    tags: true

env:
  global:
    # NPM_TOKEN
    - secure: j0nfKBK4fFPIJBE373mI+k7hFJQapXVhhfHGD19/KW3aEnhQJ6YCePBSHyLGwoWZnWhw6M77krBNb+aHw/aLTyRsRY9sZdvbZ8BLhZ9DcyAV5r4EUNGohTQdjponjdgz+LOfZv0LH/bMa2xV4evvliSdxVgJ4gtemkVVkjtcBWM4z67PmDKumzqMbWy5J3JGAtyHTTMZ7cLsPlEwjm2kccqh495QA3ntzqAID4olsFIWzb0nJGEO+B3xDowgUUvlin/kdSm2HAGwngHPG9T4OwRn9AOUZx7qrIYDiwrNXVAg8P/jZX068SEB5d87cfxTUU1Z+ezrBJy9LhtzDBaYAEajceRnpt6Gm3rl5M3vw78vjhTQEiwwgk/OKEZQtpQTz2DCaOYrRbupzhMu5GlZi0qcpO4SY6hjtWrg0v5GU1jos30iYbNj0ab7OD+YgBZCwpUCJZBIP6isdBKP4th3TsqU3QUN2d1ZhAgIJwXFNw5TQeEkK2DS4KiMdbdhfafv2EZTanqRPk46Rua5sqHnhqKrB/eZRKpwGh0d8Wdb2U/Y+hdMLbfb3D/qKqAycfCgZ3aGp0Qrlo1J8oikCzPIDo7tnn5RqhrQsRrSt/NvNxMcUkn9kMl9bym+MswINiEV+6keWHaDBIDJhTfRguWu9mLMj2sm2auC0ls+qvKQwTg=
    # NPM_EMAIL
    - secure: I1XcwxP2XJaoafSlF6++wxSDYzAJKPKsXtkAV0HssDVXwwpkNCAweuqiENfp/vg7IuWpu8IYNs1cQGe+ogwbPIE/TY0sJTyJicrMRy3DNXXUutTWvR7mALoJi1XoeKDsCTSRaQtu2Dsf59/vhes+yUd4U5bGY/5z0rEdfzYnsPaLsnThHbuUGGgM0QN0UfuhJcZ2w6xlnkbdvECwPSjfbovy9AuVpFntThTunJ03OUwhl4IaSE1vqtk5BrSdB2opznIcFvm/5imt5WFqhMujwqW1VGlJvVr2LlJ1sMmr9L4U5VpYo2PNgPBnKEdDOstj7/l0j8d2k7paaioJ1okmQiaaRdPVp6Gq9Kg8KKUwOLDKhRJSkoXlgxcYIs8lNWLBvgOHOVyyVwtEZ5ECaO7R1oR4ijK23ImUbawyIGpfIo1ODrp2gIMbDDX8F2eMR2pdusYt/HXjXbrRQgZT5zFv2yqhZVUZ+xkR+ow6wlcwif11EI2oS0U6+Y0BRJeuElqX6E7D3tnAj/MgE04ktULNTfcHGYKy/x7W91vFvijktiGKv8StVfsnbA/NWkyrbSg1p1C5S8jHo8tSAMQj1e710tC2qZBBqVUXxpYsmADRNqYS1j1SJcTqFcHHF5L0v3BEpim0zcmqBolOnetI8AfQ4gieJU1lVbQhwXY22ECT9CQ=